### ISSUE TITLE
About verifying that the results are all zeros

### ISSUE THREAD

**Issue by yangzza** [mystorm16/BSH-Det3D#4]
This is a good piece of work, when I reproduced the code I found that I ended up with all 0. But by testing the 'bsh_second.pth' provided by the author, the result is not 0. I don't know because of what. Thank you very much.

**Comment by qrzeffort** [comment]
> This is a good piece of work, when I reproduced the code I found that I ended up with all 0. But by testing the 'bsh_second.pth' provided by the author, the result is not 0. I don't know because of what. Thank you very much.

Have you solved this problem？

**Comment by yangzza** [comment]
unresolved

**Comment by s-lyu** [comment]
@yangzza , @qrzeffort 

I got the same issue, and could solve it by pointing the dictionary key 'model_state'.

https://github.com/mystorm16/BSH-Det3D/blob/00e9c7942aa2fb80f45215fd0995ae140fe47157/pcdet/models/detectors/detector3d_template.py#L408

Change this line to `model_state_dist = checkpoint['model_state']`. 
This solved the issue.
